<?php

//~ Template for account-detail.php
// variables:
//  $account - Account to be displayed

/* @var $account Account */
?>

<h3>
    <?php echo Utils::escape($account->getName()); ?>
</h3>

<table class="detail">
    <tr>
        <td>
            <tr>
                <th>Name</th>
                <td><?php echo Utils::escape($account->getName()); ?></td>
            </tr>
            <tr>
                <th>Default Customer</th>
                <td>
                    <?php if ( $account->getDefaultCustomerId() > 0 ): ?>
                        <a href="<?php echo Utils::createLink('customer-detail', array('id' => $account->getDefaultCustomerId())) ?>">
                        <?php 
                            $dao = new CustomerDao();
                            $customer = $dao->findById($account->getDefaultCustomerId());
                            if ( $customer ) {
                                echo $customer->getLastName() . ', ' . $customer->getFirstName();
                            } ?>
                        </a>
                    <?php else: ?>
                        ---
                    <?php endif; ?>
                </td>
            </tr>
            <div class="actions">
                <a href="<?php echo Utils::createLink('add-edit-account', array('id' => $account->getId())); ?>"><img src="img/action/edit.png" alt="" title="Edit it." class="icon" /></a>
                <a href="<?php echo Utils::createLink('account-delete', array('id' => $account->getId())); ?>" id="delete-link"><img src="img/action/delete.png" alt="" title="Delete it." class="icon" /></a>
            </div>
        </td>
    </tr>
</table>

<p>
    <?php 
    $backLink = Utils::createLink('account-list', array()); 
    ?>
    <a href="<?php 
    echo $backLink; 
    ?>"><img src="img/action/back.png" alt="" title="Back to the list." class="icon"/></a>&nbsp;
    <a href="<?php 
    echo $backLink; 
    ?>">To the list</a>
</p>

<div id="delete-dialog" title="Delete this Account?">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This Account will be deleted. Are you sure?</p>
</div>
<div id="change-status-dialog">
    <form id="change-status-form" method="post">
        <fieldset>
            <div class="field">
                <label>Comment:</label>
                <textarea name="comment" cols="1" rows="1"></textarea>
            </div>
        </fieldset>
    </form>
</div>
