<?php


//~ Template for add-location.php
// variables:
//  $errors - validation errors
//  $location - submitted Location
//  $edit - true for EDIT, false for ADD

function error_field($title, array $errors) {
    foreach ($errors as $error) {
        /* @var $error Error */
        if ($error->getSource() == $title) {
            return ' error-field';
        }
    }
    return '';
}

/* @var $location Location */
?>

<?php if ($edit): ?>
    <div class="actions">
        <a href="<?php echo Utils::createLink('add-location', array('id' => $location->getId(), 'clone' => true)); ?>"><img src="img/action/clone.png" alt="" title="Clone it." class="icon" /></a>
        <a href="<?php echo Utils::createLink('location-delete', array('id' => $location->getId())); ?>" id="delete-link"><img src="img/action/delete.png" alt="" title="Delete it." class="icon" /></a>
    </div>
    <div id="delete-dialog" title="Terminate this Order?">
        <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This Order will be deleted. Are you sure?</p>
    </div>
<?php endif; ?>
<br/><br/>

<h1>
    <?php if ($edit): ?>
        <?php 
        echo Utils::escape($location->getName()); 
        ?>
    <?php else: ?>
        Add new Location
    <?php endif; ?>
</h1>

<?php if (!empty($errors)): ?>
<ul class="errors">
    <?php foreach ($errors as $error): ?>
        <?php /* @var $error Error */ ?>
        <li><?php echo $error->getMessage(); ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<form action="#" method="post">
    <fieldset>
        <div class="field">
            <label>Name:</label>
            <input type="text" name="location[name]" value="<?php echo Utils::escape($location->getName()); ?>"
                   class="text<?php echo error_field('name', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Street1:</label>
            <input type="text" name="location[street1]" value="<?php echo Utils::escape($location->getStreet1()); ?>"
                   class="text<?php echo error_field('street1', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Street2:</label>
            <input type="text" name="location[street2]" value="<?php echo Utils::escape($location->getStreet2()); ?>"
                   class="text<?php echo error_field('street2', $errors); ?>"/>
        </div>
        <div class="field">
            <label>City:</label>
            <input type="text" name="location[city]" value="<?php echo Utils::escape($location->getCity()); ?>"
                   class="text<?php echo error_field('city', $errors); ?>"/>
        </div>
        <div class="field">
            <label>State:</label>
            <input type="text" name="location[state]" value="<?php echo Utils::escape($location->getState()); ?>"
                   class="text<?php echo error_field('state', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Country:</label>
            <input type="text" name="location[country]" value="<?php echo Utils::escape($location->getCountry()); ?>"
                   class="text<?php echo error_field('country', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Postal Code:</label>
            <input type="text" name="location[postal_code]" value="<?php echo Utils::escape($location->getPostalCode()); ?>"
                   class="text<?php echo error_field('postal_code', $errors); ?>"/>
        </div>
        <div  class="field">
            <label>Delivery Zone:</label>
            <select name="location[zone]">
            <?php foreach (Location::allZones() as $zone): ?>
                <option value="<?php echo $zone; ?>"
                        <?php if ($zone == $location->getZone()): ?>
                            selected="selected"
                        <?php endif; ?>
                        ><?php echo $zone; ?></option>
            <?php endforeach; ?>
            </select>
        </div>
        <div class="wrapper">
            <input type="submit" name="cancel" value="CANCEL" class="submit" />
            <input type="submit" name="save" value="<?php echo $edit ? 'EDIT' : 'ADD'; ?>" class="submit" />
        </div>
    </fieldset>
</form>
<p>
    <?php $backLink = Utils::createLink('location-list', array()); ?>
    <a href="<?php echo $backLink; ?>"><img src="img/action/back.png" alt="" title="Back to the list." class="icon"/></a>&nbsp;
    <a href="<?php echo $backLink; ?>">To the list</a>
</p>