<?php


//~ Template for add-location.php
// variables:
//  $errors - validation errors
//  $location - submitted Location
//  $edit - true for EDIT, false for ADD

function error_field($title, array $errors) {
    foreach ($errors as $error) {
        /* @var $error Error */
        if ($error->getSource() == $title) {
            return ' error-field';
        }
    }
    return '';
}

/* @var $location Location */
?>

<h1>
    <?php if ($edit): ?>
        <?php 
        echo Utils::escape($location->getName()); 
        ?>
    <?php else: ?>
        Add new Location
    <?php endif; ?>
</h1>

<?php if (!empty($errors)): ?>
<ul class="errors">
    <?php foreach ($errors as $error): ?>
        <?php /* @var $error Error */ ?>
        <li><?php echo $error->getMessage(); ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<form action="#" method="post">
    <fieldset>
        <div class="field">
            <label>Name:</label>
            <input type="text" name="location[name]" value="<?php echo Utils::escape($location->getName()); ?>"
                   class="text<?php echo error_field('name', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Street1:</label>
            <input type="text" name="location[street1]" value="<?php echo Utils::escape($location->getStreet1()); ?>"
                   class="text<?php echo error_field('street1', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Street2:</label>
            <input type="text" name="location[street2]" value="<?php echo Utils::escape($location->getStreet2()); ?>"
                   class="text<?php echo error_field('street2', $errors); ?>"/>
        </div>
        <div class="field">
            <label>City:</label>
            <input type="text" name="location[city]" value="<?php echo Utils::escape($location->getCity()); ?>"
                   class="text<?php echo error_field('city', $errors); ?>"/>
        </div>
        <div class="field">
            <label>State:</label>
            <input type="text" name="location[state]" value="<?php echo Utils::escape($location->getState()); ?>"
                   class="text<?php echo error_field('state', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Country:</label>
            <input type="text" name="location[country]" value="<?php echo Utils::escape($location->getCountry()); ?>"
                   class="text<?php echo error_field('country', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Postal Code:</label>
            <input type="text" name="location[postal_code]" value="<?php echo Utils::escape($location->getPostalCode()); ?>"
                   class="text<?php echo error_field('postal_code', $errors); ?>"/>
        </div>
        <div class="wrapper">
            <input type="submit" name="cancel" value="CANCEL" class="submit" />
            <input type="submit" name="save" value="<?php echo $edit ? 'EDIT' : 'ADD'; ?>" class="submit" />
        </div>
    </fieldset>
</form>
