<?php


//~ Template for add-edit-item.php
// variables:
//  $errors - validation errors
//  $item - submitted Item
//  $edit - true for EDIT, false for ADD

function error_field($title, array $errors) {
    foreach ($errors as $error) {
        /* @var $error Error */
        if ($error->getSource() == $title) {
            return ' error-field';
        }
    }
    return '';
}

/* @var $item Item */
?>

<?php if ($edit): ?>
    <div class="actions">
        <a href="<?php echo Utils::createLink('add-edit-item', array('id' => $item->getId(), 'clone' => true)); ?>"><img src="img/action/clone.png" alt="" title="Clone it." class="icon" /></a>
        <a href="<?php echo Utils::createLink('item-delete', array('id' => $item->getId())); ?>" id="delete-link"><img src="img/action/delete.png" alt="" title="Delete it." class="icon" /></a>
    </div>
    <div id="delete-dialog" title="Terminate this Order?">
        <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This Order will be deleted. Are you sure?</p>
    </div>
<?php endif; ?>
<br/><br/>

<h1>
    <?php if ($edit): ?>
        <?php echo Utils::escape($item->getCode() . ' - ' . $item->getName()); ?>
    <?php else: ?>
        Add new Item
    <?php endif; ?>
</h1>

<?php if (!empty($errors)): ?>
<ul class="errors">
    <?php foreach ($errors as $error): ?>
        <?php /* @var $error Error */ ?>
        <li><?php echo $error->getMessage(); ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<form action="#" method="post">
    <fieldset>
        <div class="field">
            <label>Code:</label>
            <input type="text" name="item[code]" value="<?php echo Utils::escape($item->getCode()); ?>"
                   class="text<?php echo error_field('code', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Name:</label>
            <input type="text" name="item[name]" value="<?php echo Utils::escape($item->getName()); ?>"
                   class="text<?php echo error_field('name', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Size:</label>
            <input type="number" step="0.1" min="0.1" name="item[size]" value="<?php echo Utils::escape($item->getSize()); ?>"
                   class="text<?php echo error_field('size', $errors); ?>"/>
        </div>
        <div  class="field">
            <label>Unit:</label>
            <select name="item[unit]">
            <?php foreach (Item::allUnits() as $unit): ?>
                <option value="<?php echo $unit; ?>"
                        <?php if ($unit == $item->getUnit()): ?>
                            selected="selected"
                        <?php endif; ?>
                        ><?php echo $unit; ?></option>
            <?php endforeach; ?>
            </select>
        </div>
        <div class="wrapper">
            <input type="submit" name="cancel" value="CANCEL" class="submit" />
            <input type="submit" name="save" value="<?php echo $edit ? 'UPDATE' : 'ADD'; ?>" class="submit" />
        </div>
    </fieldset>
</form>
<p>
    <?php 
    $backLink = Utils::createLink('item-list', array()); 
    ?>
    <a href="<?php 
    echo $backLink; 
    ?>"><img src="img/action/back.png" alt="" title="Back to the list." class="icon"/></a>&nbsp;
    <a href="<?php 
    echo $backLink; 
    ?>">To the list</a>
</p>

