<?php


//~ Template for add-edit-account.php
// variables:
//  $errors - validation errors
//  $account - submitted Account
//  $edit - true for EDIT, false for ADD

function error_field($title, array $errors) {
    foreach ($errors as $error) {
        /* @var $error Error */
        if ($error->getSource() == $title) {
            return ' error-field';
        }
    }
    return '';
}

/* @var $account Account */
?>

<div class="actions">
    <a href="<?php echo Utils::createLink('add-edit-account', array('id' => $account->getId(), 'clone' => true)); ?>"><img src="img/action/clone.png" alt="" title="Clone it." class="icon" /></a>
    <a href="<?php echo Utils::createLink('account-delete', array('id' => $account->getId())); ?>" id="delete-link"><img src="img/action/delete.png" alt="" title="Delete it." class="icon" /></a>
</div>
<div id="delete-dialog" title="Delete this Account?">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This Order will be deleted. Are you sure?</p>
</div>

<br/><br/>

<h1>
    <?php if ($edit): ?>
        <?php echo Utils::escape($account->getName()); ?>
    <?php else: ?>
        Add new Account
    <?php endif; ?>
</h1>

<?php if (!empty($errors)): ?>
<ul class="errors">
    <?php foreach ($errors as $error): ?>
        <?php /* @var $error Error */ ?>
        <li><?php echo $error->getMessage(); ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<form action="#" method="post">
    <fieldset>
        <div class="field">
            <label>Name:</label>
            <input type="text" name="account[name]" value="<?php echo Utils::escape($account->getName()); ?>"
                   class="text<?php echo error_field('name', $errors); ?>"/>
        </div>
        <div class="field">
        <p>If this account will always be associated with one customer, select the customer.  Otherwise leave the customer as "Varied".
        </div>
        <div  class="field">
            <label>Customer:</label>
            <select name="account[default_customer_id]">
                <option value="0" 
                        <?php if (0 == $account->getDefaultCustomerId()): ?>
                            selected="selected"
                        <?php endif; ?>
                            >Varied</option>
            <?php foreach (Utils::getAllCustomerIdAndName() as $cust): ?>
                <option value="<?php echo $cust[id]; ?>"
                        <?php if ($cust[id] == $account->getDefaultCustomerId()): ?>
                            selected="selected"
                        <?php endif; ?>
                        ><?php echo $cust[last_name] . ", " . $cust[first_name] . ", " . $cust[id]; ?></option>
            <?php endforeach; ?>
            </select>
        </div>
        <div class="wrapper">
            <input type="submit" name="cancel" value="CANCEL" class="submit" />
            <input type="submit" name="save" value="<?php echo $edit ? 'UPDATE' : 'ADD'; ?>" class="submit" />
        </div>
    </fieldset>
</form>
<p>
    <?php 
    $backLink = Utils::createLink('account-list', array()); 
    ?>
    <a href="<?php 
    echo $backLink; 
    ?>"><img src="img/action/back.png" alt="" title="Back to the list." class="icon"/></a>&nbsp;
    <a href="<?php 
    echo $backLink; 
    ?>">To the list</a>
</p>

