<?php


//~ Template for customer-list.php
// variables:
//  $title - page title
//  $items - Locations to be displayed

?>

<table class="detail">
    <tr>
        <th>Actions</th>
        <td>
            <div class="actions">
                <a href="<?php 
                echo Utils::createLink('add-customer'); 
                ?>"><img src="img/action/add.png" alt="" title="Add Customer" class="icon" /></a>
            </div>
        </td>
    </tr>
</table>

<?php if (empty($customers)): ?>
    <p>No customers found.</p>
<?php else: ?>
    <ul class="customer-list">
        <?php foreach ($customers as $customer): ?>
            <?php /* @var $customer Item */ ?>
            <li>
                <h3><a href="<?php echo Utils::createLink('customer-detail', array('id' => $customer->getId())) ?>">
                    <?php echo Utils::escape($customer->getFirstName()) . ' ' . Utils::escape($customer->getLastName()); ?>
                    </a></h3>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
