<?php


//~ Template for edit-working-order.php
// variables:
//  $errors - validation errors
//  $order - submitted WorkingOrder
//  $edit - true for EDIT, false for ADD

function error_field($title, array $errors) {
    foreach ($errors as $error) {
        /* @var $error Error */
        if ($error->getSource() == $title) {
            return ' error-field';
        }
    }
    return '';
}

/* @var $order WorkingOrder */
?>

<div class="actions">
    <a href="<?php echo Utils::createLink('working-order-delete', array('id' => $order->getId())); ?>" id="delete-link"><img src="img/action/delete.png" alt="" title="Delete it." class="icon" /></a>
</div>
<div id="delete-dialog" title="Delete this Working Order?">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This Order will be deleted. Are you sure?</p>
</div>

<br/><br/>
<h1>
    <?php if ($edit): ?>
        <?php 
        echo "Working Order: " . Utils::escape($order->getId()); 
        ?>
    <?php else: ?>
        Add new Order
    <?php endif; ?>
</h1>

<?php if (!empty($errors)): ?>
<ul class="errors">
    <?php foreach ($errors as $error): ?>
        <?php /* @var $error Error */ ?>
        <li><?php echo $error->getMessage(); ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<form action="#" method="post">
    <fieldset>
        <div  class="field">
            <label>Account:</label>
            <input type="text" value="
                   <?php echo $order->getAccountName(); ?>" disabled />
        </div>
        <div  class="field">
            <label>Customer:</label>
            <input type="text" value="
                   <?php echo $order->getCustomerName(); ?>" disabled />
        </div>
        <div  class="field">
            <label>Item:</label>
            <select name="order[item_id]">
            <?php foreach (Utils::getAllItems() as $it): ?>
                <option value="<?php echo $it->getId(); ?>"
                        <?php if ($it->getId() == $order->getItemId()): ?>
                            selected="selected"
                        <?php endif; ?>
                        ><?php echo Utils::escape($it->getCode() . ' - ' . $it->getName()
                                . ' - ' . $it->getSize() . ' ' . $it->getUnit() ); ?></option>
            <?php endforeach; ?>
            </select>
        </div>
        <div class="field">
            <label>Quantity:</label>
            <input type="number" name="order[quantity]" 
                <?php if ($edit) { echo 'value="' . $order->getQuantity(); } ?>"
                   class="text<?php echo error_field('quantity', $errors); ?>"/>
        </div>
        <div  class="field">
            <label>Location:</label>
            <select name="order[pickup_location_id]">
            <?php foreach (Utils::getAllLocationIdAndName() as $loc): ?>
                <option value="<?php echo $loc[id]; ?>"
                        <?php if ($loc[id] == $order->getLocationId()): ?>
                            selected="selected"
                        <?php endif; ?>
                        ><?php echo $loc[name] . ", " . $loc[id]; ?></option>
              
            <?php endforeach; ?>
            </select>
        </div>
        <div class="field">
            <label>Delivery Date:</label>
            <input type="text" name="order[delivery_date]" 
                <?php if ($edit) { echo 'value="' . Utils::formatDate($order->getDeliveryDate()); } ?>"
                   class="text datepicker<?php echo error_field('delivery_date', $errors); ?>" />
        </div>
        <div class="field">
            <label>Delivery Time:</label>
            <input type="time" name="order[delivery_time]" 
                <?php if ($edit) { echo 'value="' . $order->getDeliveryTime()->format( 'H:i' ); } ?>"
                   class="text<?php echo error_field('delivery_time', $errors); ?>" />
        </div>
        <div class="wrapper">
            <input type="submit" name="cancel" value="CANCEL" class="submit" />
            <input type="submit" name="save" value="<?php echo $edit ? 'EDIT' : 'ADD'; ?>" class="submit" />
        </div>
    </fieldset>
</form>
<p>
    <?php $backLink = Utils::createLink('working-order-list', array()); ?>
    <a href="<?php echo $backLink; ?>"><img src="img/action/back.png" alt="" title="Back to the list." class="icon"/></a>&nbsp;
    <a href="<?php echo $backLink; ?>">To the list</a>
</p>

