<?php

?>
<h1>Order Tracking</h1>

<ul class="p">
    This application allows you to:
    <li>add/edit customers and their orders
        <ul>
            <li>orders can be entered as a subscription</li>
            <li>working orders (the actual items to be delivered) can be edited individually, without changing the subscription</li>
        </ul></li>
    
    <li>view orders
        <ul>
            <li>for a given day or week</li>
            <li>for a given customer</li>
        </ul></li>
    <li>review order history</li>
    <li>add/edit items that can be ordered</li>
    <li>add/edit pick up locations for orders</li>
</ul>
<p class="p">Coming soon...</p>
<ul>
    <li>ingredients needed to make the orders for a given period of days</li>
</ul>
