<?php


//~ Template for item-list.php
// variables:
//  $title - page title
//  $items - Items to be displayed

?>

<table class="detail">
    <tr>
        <th>Actions</th>
        <td>
            <div class="actions">
                <a href="<?php 
                echo Utils::createLink('add-edit-item'); 
                ?>"><img src="img/action/add.png" alt="" title="Add Item" class="icon" /></a>
            </div>
        </td>
    </tr>
</table>

<?php if (empty($items)): ?>
    <p>No items found.</p>
<?php else: ?>
    <table class="detail">
        <tr>
            <th>Code+Name</th>
            <th>Size</th>
            <th>Unit</th>
        </tr>
        </th>
        <?php foreach ($items as $item): ?>
            <?php /* @var $item Item */ ?>
            <tr>
                <td>
                    <a href="<?php echo Utils::createLink('item-detail', array('id' => $item->getId())) ?>">
                    <?php echo Utils::escape($item->getCode()); ?> -- <?php echo Utils::escape($item->getName()); ?>
                    </a>
                </td>
                <td>
                    <?php echo Utils::escape($item->getSize()) ?>
                </td>
                <td>
                    <?php echo Utils::escape($item->getUnit()) ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>

