<?php

//~ Template for location_detail.php
// variables:
//  $location - Location to be displayed

/* @var $location Location */
?>

<h1>
    <?php echo Utils::escape($location->getName()); ?>
</h1>

<table class="detail">
    <tr>
        <th>Actions</th>
        <td>
            <tr>
                <th>Street1</th>
                <td><?php echo Utils::escape($location->getStreet1()); ?></td>
            </tr>
            <tr>
                <th>Street2</th>
                <td><?php echo Utils::escape($location->getStreet2()); ?></td>
            </tr>
            <tr>
                <th>City</th>
                <td><?php echo Utils::escape($location->getCity()); ?></td>
            </tr>
            <tr>
                <th>State</th>
                <td><?php echo Utils::escape($location->getState()); ?></td>
            </tr>
            <tr>
                <th>Postal Code</th>
                <td><?php echo Utils::escape($location->getPostalCode()); ?></td>
            </tr>
            <tr>
                <th>Country</th>
                <td><?php echo Utils::escape($location->getCountry()); ?></td>
            </tr>
            <div class="actions">
                <a href="<?php echo Utils::createLink('add-location', array('id' => $location->getId())); ?>"><img src="img/action/edit.png" alt="" title="Edit it." class="icon" /></a>
                <a href="<?php echo Utils::createLink('location-delete', array('id' => $location->getId())); ?>" id="delete-link"><img src="img/action/delete.png" alt="" title="Delete it." class="icon" /></a>
            </div>
        </td>
    </tr>
</table>

<p>
    <?php $backLink = Utils::createLink('location-list', array()); ?>
    <a href="<?php echo $backLink; ?>"><img src="img/action/back.png" alt="" title="Back to the list." class="icon"/></a>&nbsp;
    <a href="<?php echo $backLink; ?>">To the list</a>
</p>

<div id="delete-dialog" title="Delete this Location?">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This Location will be deleted. Are you sure?</p>
</div>
<div id="change-status-dialog">
    <form id="change-status-form" method="post">
        <fieldset>
            <div class="field">
                <label>Comment:</label>
                <textarea name="comment" cols="1" rows="1"></textarea>
            </div>
        </fieldset>
    </form>
</div>
