<?php


//~ Template for location-list.php
// variables:
//  $title - page title
//  $items - Locations to be displayed

?>

<table class="detail">
    <tr>
        <th>Actions</th>
        <td>
            <div class="actions">
                <a href="<?php 
                echo Utils::createLink('add-location'); 
                ?>"><img src="img/action/add.png" alt="" title="Add Location" class="icon" /></a>
            </div>
        </td>
    </tr>
</table>

<?php if (empty($locations)): ?>
    <p>No locations found.</p>
<?php else: ?>
    <ul class="location-list">
        <?php foreach ($locations as $location): ?>
            <?php /* @var $location Item */ ?>
            <li>
                <h3><a href="<?php echo Utils::createLink('add-location', array('id' => $location->getId())) ?>">
                    <?php echo Utils::escape($location->getName()); ?>
                    </a></h3>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
