<?php


//~ Template for order-list.php
// variables:
//  $title - page title
//  $items - Locations to be displayed

?>

<div id="twocolwrapper">
    <div id="column1">
        <form action="#" method="post">
            <fieldset>
                <div  class="field">
                    <label>Customer:</label>
                    <select name="customer_id">
                        <option value="0" >All Customers</option>
                    <?php foreach (Utils::getAllCustomerIdAndName() as $cust): ?>
                        <option value="<?php echo $cust[id]; ?>"
                                <?php if ($cust[id] == $_POST['customer_id']): ?>
                                    selected="selected"
                                <?php endif; ?>
                                ><?php echo $cust[last_name] . ", " . $cust[first_name] . ", " . $cust[id]; ?></option>
                    <?php endforeach; ?>
                    </select>
                </div>
                <div class="wrapper">
                    <input type="submit" name="save" value="FILTER" class="submit" />
                </div>
            </fieldset>
        </form>
    </div>
    <div id="sidebar">
        <form action="#" method="post">
            <label>Count:  </label><?php echo sizeof( $orders ); ?>
            <div class="wrapper">
                <input type="hidden" name="customer_id" value="<?php 
                echo $_POST['customer_id']; 
                ?>">
                <input type="submit" name="download_orders" value="Download" class="submit-left" />
            </div>
    </div>
    <div id="cleared"></div>
</div>

<?php if (empty($orders)): ?>
    <p>No orders found.</p>
<?php else: ?>
    <table class="detail">
        <tr>
            <th>ID</th> 
            <th>Customer</th>
            <th>Item</th>
            <th>Quantity</th>
            <th>Location</th>
            <th>Start</th>
            <th>End</th>
            <th>Frequency</th>
            <th>Day</th>
        </tr>
        </th>
        <?php foreach ($orders as $order): ?>
            <?php /* @var $order Item */ ?>
            <tr>
                <td>
                    <a href="<?php echo Utils::createLink('order-detail', array('id' => $order->getId())) ?>">
                        <?php echo $order->getId() ?></a>
                </td>
                <td>
                    <a href="<?php echo Utils::createLink('customer-detail', array('id' => $order->getCustomerId())) ?>">
                    <?php echo Utils::escape($order->getCustomerName()) ?></a>
                </td>
                <td>
                    <?php 
                    $it = $order->getItem();
                    if ( $it ) {
                        echo Utils::escape($it->getType() . ' - ' . $it->getSubtype()
                                . ' - ' . $it->getSize() . ' ' . $it->getUnit() ); 
                    }?>
                </td>
                <td>
                    <?php echo Utils::escape($order->getQuantity()) ?>
                </td>
                <td>
                    <?php echo Utils::escape($order->getLocationName()) ?>
                </td>
                <td>
                    <?php echo Utils::escape(Utils::formatDate($order->getStartDate())) ?>
                </td>
                <td>
                    <?php echo Utils::escape(Utils::formatDate($order->getEndDate())) ?>
                </td>
                <td>
                    <?php echo Utils::escape($order->getFrequency()) ?>
                </td>
                <td>
                    <?php 
                    if ( $order->getFrequency() == 'DAILY') {
                        echo '---';
                    } else {
                        echo Utils::escape($order->getDayOfWeek()); 
                    }
                    ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
