<?php

//~ Template for order_detail.php
// variables:
//  $order - Order to be displayed

/* @var $order Order */
?>


<table class="detail">
    <tr>
        <td>
            <tr>
                <th>Customer</th>
                <td>
                        <a href="<?php 
                            echo Utils::createLink('customer-detail', array('id' => $order->getCustomerId())); 
                    ?>"><?php 
                        echo Utils::escape($order->getCustomerName()); 
                        ?></a>
                    </td>
            </tr>
            <tr>
                <th>Item</th>
                <td><?php 
                    $it = $order->getItem();
                    if ( $it ) {
                        echo Utils::escape($it->getType() . ' - ' 
                                . $it->getSubtype() . ' - ' . $it->getSize() 
                                . ' ' . $it->getUnit()) ; 
                    }
                    ?></td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td><?php 
                    echo Utils::escape($order->getQuantity()); 
                    ?></td>
            </tr>
            <tr>
                <th>Start Date</th>
                <td><?php 
                    echo Utils::escape(Utils::formatDate($order->getStartDate())); 
                    ?></td>
            </tr>
            <tr>
                <th>End Date</th>
                <td><?php echo Utils::escape(Utils::formatDate($order->getEndDate())); ?></td>
            </tr>
            <tr>
                <th>Frequency</th>
                <td><?php echo Utils::escape($order->getFrequency()); ?></td>
            </tr>
            <?php if ($order->getFrequency() == 'N-WEEKLY') : ?>
            <tr>
                <th>N Weeks</th>
                <td><?php echo Utils::escape($order->getNWeekly()); ?></td>
            </tr>
            <?php endif ?>
            <?php if ($order->getFrequency() == 'DAILY') : ?>
            <tr>
                <th>Skip Days</th>
                <td><?php 
                $multi = false;
                foreach ( $order->allDays() as $d ) {
                    if ( $order->skipDay( $d ) ) {
                        if ( $multi ) {
                            echo ', ';
                        }
                        echo $d; 
                        $multi = true;
                    }
                }
                ?></td>
            </tr>
            <?php else : ?>
            <tr>
                <th>Day of Week</th>
                <td><?php echo Utils::escape($order->getDayOfWeek()); ?></td>
            </tr>
            <?php endif ?>
            <tr>
                <th>Location</th>
                <td><?php echo Utils::escape($order->getLocationName()); ?></td>
            </tr>
            <tr>
                <th>Pickup Time</th>
                <td><?php echo $order->getPickupTime()->format( 'H:i' ); ?></td>
            </tr>
            <tr>
                <th>Order Date</th>
                <td><?php echo Utils::escape(Utils::formatDateTime($order->getOrderDate())); ?></td>
            </tr>
            <tr>
                <th>Modified by</th>
                <td><?php 
                echo Utils::escape(Utils::getUserById($order->getUserId())->getUsername()); 
                ?></td>
            </tr>
            <div class="actions">
                <a href="<?php echo Utils::createLink('add-order', array('id' => $order->getId())); ?>"><img src="img/action/edit.png" alt="" title="Edit it." class="icon" /></a>
                <a href="<?php echo Utils::createLink('order-delete', array('id' => $order->getId())); ?>" id="delete-link"><img src="img/action/delete.png" alt="" title="Delete it." class="icon" /></a>
            </div>
        </td>
    </tr>
</table>

<p>
    <?php $backLink = Utils::createLink('order-list', array()); ?>
    <a href="<?php echo $backLink; ?>"><img src="img/action/back.png" alt="" title="Back to the list." class="icon"/></a>&nbsp;
    <a href="<?php echo $backLink; ?>">To the list</a>
</p>

<div id="delete-dialog" title="Delete this Order?">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This Order will be deleted. Are you sure?</p>
</div>
<div id="change-status-dialog">
    <form id="change-status-form" method="post">
        <fieldset>
            <div class="field">
                <label>Comment:</label>
                <textarea name="comment" cols="1" rows="1"></textarea>
            </div>
        </fieldset>
    </form>
</div>
