<?php

//~ Template for working-order-detail.php
// variables:
//  $order - WorkingOrder to be displayed

/* @var $order WorkingOrder */
?>


<table class="detail">
    <tr>
        <td>
            <tr>
                <th>Working Order</th>
                <td><?php 
                    echo Utils::escape($order->getId()) ; 
                    ?></td>
            </tr>
            <tr>
                <th>Order</th>
                <td>
                        <a href="<?php 
                            echo Utils::createLink('order-detail', array('id' => $order->getOrderId())); 
                    ?>"><?php 
                        echo Utils::escape($order->getOrderId()); 
                        ?></a>
                    </td>
            </tr>
            <tr>
                <th>Customer</th>
                <td>
                        <a href="<?php 
                            echo Utils::createLink('customer-detail', array('id' => $order->getCustomerId())); 
                    ?>"><?php 
                        echo Utils::escape($order->getCustomerName()); 
                        ?></a>
                    </td>
            </tr>
            <tr>
                <th>Item</th>
                <td><?php 
                    $it = $order->getItem();
                    if ( $it ) {
                        echo Utils::escape($it->getType() . ' - ' . $it->getSubtype()
                                . ' - ' . $it->getSize() . ' ' . $it->getUnit() ); 
                    } ?></td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td><?php 
                    echo Utils::escape($order->getQuantity()); 
                    ?></td>
            </tr>
            <tr>
                <th>Delivery Date</th>
                <td><?php 
                    echo $order->getDeliveryDate()->format( 'Y-m-d' ); 
                    ?></td>
            </tr>
            <tr>
                <th>Modified Date</th>
                <td><?php echo Utils::escape(Utils::formatDateTime($order->getModifiedDate())); ?></td>
            </tr>
            <tr>
                <th>Modifying User</th>
                <td><?php 
                echo Utils::escape(Utils::getUserById( $order->getUserId() )->getUsername() ); 
                ?></td>
            </tr>
            <tr>
                <th>Location</th>
                <td><?php echo Utils::escape($order->getLocationName()); ?></td>
            </tr>
            <div class="actions">
                <a href="<?php echo Utils::createLink('edit-working-order', array('id' => $order->getId())); ?>"><img src="img/action/edit.png" alt="" title="Edit it." class="icon" /></a>
                <a href="<?php echo Utils::createLink('working-order-delete', array('id' => $order->getId())); ?>" id="delete-link"><img src="img/action/delete.png" alt="" title="Delete it." class="icon" /></a>
            </div>
        </td>
    </tr>
</table>

<p>
    <?php $backLink = Utils::createLink('working-order-list', array()); ?>
    <a href="<?php echo $backLink; ?>"><img src="img/action/back.png" alt="" title="Back to the list." class="icon"/></a>&nbsp;
    <a href="<?php echo $backLink; ?>">To the list</a>
</p>

<div id="delete-dialog" title="Delete this WorkingOrder?">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This WorkingOrder will be deleted. Are you sure?</p>
</div>
<div id="change-status-dialog">
    <form id="change-status-form" method="post">
        <fieldset>
            <div class="field">
                <label>Comment:</label>
                <textarea name="comment" cols="1" rows="1"></textarea>
            </div>
        </fieldset>
    </form>
</div>
